apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb-server
  type: ClusterIP
  ports:
    - name: mongodbaccess
      port: 27017
      targetPort: 27017
