apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb-server
  serviceName: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-server
    spec:
      containers:
      - name: mongodb-server
        image: mongo
        ports:
        - containerPort: 27017
          name: mongodbaccess
        volumeMounts:
        - name: dbmount
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: dbmount
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
